import Head from "next/head";
import Image from "next/image";
import GlassCard from "../components/UI/GlassCard";
import styles from "../styles/Home.module.css";
import ProjectsData from "../components/ProjectsData";
import Name from "../components/Name";

export default function Home() {
  const HardData = ProjectsData;

  let content = <p>Found no projects.</p>;
  content = HardData.map((project, index) => {
    return (
      <GlassCard
        key={project.id}
        id={index+1}
        title={project.title}
        description={project.description}
        href={project.href}
      />
    );
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Roberto Cisneros React Dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Name />
        <div className={styles.grid}>{content}</div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://robcisneros.netlify.app/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Made it by Roberto Cisneros
          <span className={styles.logo}>
          </span>
        </a>
      </footer>
    </div>
  );
}
