import Head from "next/head";
import Image from "next/image";
import GlassCard from "../components/UI/GlassCard";
import styles from "../styles/Home.module.css";

export default function Home() {
  const HardData = [
    {
      title: "Learn 1",
      description: "Learn about Next.js in an interactive course with quizzes!",
      href: "https://nextjs.org/learn",
      id: 1,
    },
    {
      title: "Learn 2",
      description: "Learn about Next.js in an interactive course with quizzes!",
      href: "https://nextjs.org/learn",
      id: 2,
    },
    {
      title: "Learn 3",
      description: "Learn about Next.js in an interactive course with quizzes!",
      href: "https://nextjs.org/learn",
      id: 3,
    },
    {
      title: "Learn 4",
      description: "Learn about Next.js in an interactive course with quizzes!",
      href: "https://nextjs.org/learn",
      id: 4,
    },
  ];

  let content = <p>Found no projects.</p>;

  content = HardData.map((project) => (
    <GlassCard
      key={project.id}
      id={project.id}
      title={project.title}
      description={project.description}
      href={project.href}
    />
  ));

  return (
    <div className={styles.container}>
      <Head>
        <title>Roberto Cisneros React Dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Roberto Cisneros, React Dev</h1>

        <div className={styles.grid}>
          {content}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Made it by Roberto Cisneros
          <span className={styles.logo}>
            <Image src="/obenmed.svg" alt="Vercel Logo" width={30} height={30} />
          </span>
        </a>
      </footer>
    </div>
  );
}
